### ISSUE TITLE
JSON-based package for Arduino 1.6.5+ Boards Manager?

### ISSUE THREAD

**Issue by rei-vilo** [LowPowerLab/Moteino#1]
Hi!

Do you plan to bundle the Motion files in a JSON-based package for Arduino 1.6.5+ Boards Manager?

Thank you,

**Comment by whmountains** [comment]
Apparently the answer is yes.  The boards manager URL is: https://lowpowerlab.github.io/MoteinoCore/package_LowPowerLab_index.json
