### ISSUE TITLE
R6 eagle files?

### ISSUE THREAD

**Issue by fatmcgav** [LowPowerLab/Moteino#5]
Hi @LowPowerLab 

Firstly, thank-you for all your hard work on Moteino. 

Are you intending to publish the R6 eagle files?

Cheers

**Comment by LowPowerLab** [comment]
Not sure at this point. The R5 is almost identical. See forum for schematic.
Not an issue so closing this, please ask similar questions in the forum, thanks.

**Comment by fatmcgav** [comment]
No worries, cheers for quick response.
